Shop_platform/Shop_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .settings import MEDIA_URL, MEDIA_ROOT 
from django.conf.urls.static import static
from shop_platform_app.views import home_view



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("home/", home_view, name="home_view"),
    path("api/", include("api.urls", namespace="shops-api")),
    path("shops/", include("shops.urls")),
    path("orders/", include("orders.urls")),
    path("notifications/", include("notifications.urls")),
	path("password_reset/", auth_views.PasswordResetView.as_view(), name="password-reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(MEDIA_URL, document_root=MEDIA_ROOT)

Shop_platform/api/urls.py
from rest_framework.routers import DefaultRouter 
from .views import ShopViewSet
from shops.models import Shop
from .serializers import ShopSerializer
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "api"

router = DefaultRouter()

router.register("Shops", ShopViewSet, basename="shop")
#router.register("products", ProductViewSet)

shop_list = ShopViewSet.as_view({"get":"list", "post":"create"})
shop_detail = ShopViewSet.as_view({"get":"retrieve"})

urlpatterns = [

    path("shops/", shop_list, name="shop-list"),
    path("shops/<slug:slug>/", shop_detail, name="shop-detail"),

]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=["json"])

Shop_platform/shops/urls.py
from django.urls import path, include
from .views import (
						create_shop_view,
						detail_shop_view,
						list_shop_view,
						create_product_view,
						detail_product_view,
						update_product_view,
						delete_product_view,
						shop_list_view,
						)
from django.conf.urls.static import static
from Shop_platform import settings



app_name = "shops"

urlpatterns = [
		
		path("creation/", create_shop_view, name="creation-shop"),
		path("shop/<slug:shop_slug>/", detail_shop_view, name="detail-shop"),
		path("list/", list_shop_view, name="shop-list"),
		path("shop/products/creation", create_product_view, name="create-product"),
		path("shop/<slug:shop_slug>/products/<slug:slug>/", detail_product_view, name="detail-product"),
		path("shop/<slug:shop_slug>/products/<slug:slug>/update", update_product_view, name="update-product"),
		path("shop/<slug:shop_slug>/products/<slug:slug>/delete", delete_product_view, name="delete-product"),
		path("shoppingcart/", shop_list_view, name="shopping-cart"),
		]

Shop_platform/shops/models.py
from django.db import models
from users.models import Profile
from django.urls import reverse 
from django.utils.text import slugify
from django.core.files.storage import FileSystemStorage
from PIL import Image
# Create your models here.

class Shop(models.Model):

	name = models.CharField(max_length=30)
	owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
	slug = models.SlugField(unique=True)

	def save(self, *args, **kwargs):

		self.slug = slugify(self.name)
		super().save(*args, **kwargs)

	def __str__(self):

		return f"{self.name} created by {self.owner}"

category_product = (

			("1", "Sport"),
			("2", "Tech"),
			("3", "Health")
			)

#filestorage = FileSystemStorage(location="/media/productsphotos")

class Product(models.Model):

	name = models.CharField(max_length=100)
	image = models.ImageField(upload_to="productsphotos", default="nopicture.jpeg")
	slug = models.SlugField(unique=True)
	date = models.DateField(auto_now_add=True)
	seller = models.ForeignKey(Profile, on_delete=models.CASCADE)
	available = models.BooleanField()
	price = models.DecimalField(max_digits=7, decimal_places=2, default=10.00)
	description = models.TextField(max_length=200)
	category = models.CharField(max_length=10, choices=category_product, default="Sport")
	quantity = models.IntegerField(default=1)
	shop = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name="products")

	def __str__(self):

		return f"{self.pk} :{self.name}"

	def save(self, *args, **kwargs):

		self.slug = slugify(self.name)
		super().save(*args, **kwargs)

		size = 40, 40
		image = Image.open(self.image.path)
		image.thumbnail(size)
		image.save(self.image.path)

	def get_absolute_url(self):

		return reverse("shops:detail-product", kwargs={"shop_slug": self.shop.slug, "slug": self.slug})

Shop_platform/shops/forms.py
from shops.models import Shop, Product
from django import forms

class Shop_Form(forms.ModelForm):

	class Meta:

		model = Shop
		fields = ["name"]

class Product_Form(forms.ModelForm):

	class Meta:

		model = Product
		fields = ["name", "image", "price", "description", "category"]


class Update_Form(forms.Form):

	choices = ((quantity, quantity) for quantity in range(1, 99))
	quantity = forms.ChoiceField(choices=choices)

Shop_platform/shops/views.py
from django.shortcuts import render
from .models import Shop, Product
from .forms import Shop_Form, Product_Form, Update_Form
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from users.models import Profile
from .shop_list import Shopping_Cart
from ast import literal_eval
from django.core.files.storage import FileSystemStorage
from orders.models import Address, Order
from notifications.signals import order_creation



# Create your views here.


def create_shop_view(request):
	
	form = Shop_Form()
	owner = get_object_or_404(Profile, user=request.user)

	if request.method == "POST":

		form =  Shop_Form(request.POST)

		if form.is_valid():

			form.instance.owner = owner
			form.save()
			shop_slug = form.instance.slug

			return redirect(reverse("shops:detail-shop", kwargs={"shop_slug": shop_slug}))

	return render(request, "shops/create_shop.html", {"form":form})

def detail_shop_view(request, shop_slug):

	shop = None 
	products = []
	profile = get_object_or_404(Profile, user=request.user)

	if shop_slug:

		shop = Shop.objects.get(slug=shop_slug)
		products = Product.objects.all().filter(available=True, shop=shop)

	return render(request, "shops/detail_shop.html", {"shop": shop, "products": products, "profile":profile})

def list_shop_view(request):

	shops = Shop.objects.all()

	return render(request, "shops/list_shop.html", {"shops": shops})

def create_product_view(request):

	form = Product_Form()
	profile = get_object_or_404(Profile, user=request.user)
	shop = Shop.objects.get(owner=profile)

	if request.method == "POST":

		form = Product_Form(request.POST, request.FILES)
		print(request.FILES)

		if form.is_valid():
			image = request.FILES["image"]
			form.instance.image = image
			form.instance.seller = shop.owner
			form.instance.available = True
			form.instance.shop = shop

			form.save()

			return redirect(reverse("shops:detail-shop", kwargs={"shop_slug": form.instance.shop.slug})) #redirect somewhere

	return render(request, "product/product_creation.html", {"form": form, "shop":shop})


def detail_product_view(request, shop_slug, slug):

	shop = get_object_or_404(Shop, slug=shop_slug)
	cart = Shopping_Cart(request)

	if shop_slug and slug:

		product = Product.objects.get(slug=slug, shop=shop)
		
		if request.method == "POST":

			cart.add_product(product.id) 

	return render(request, "product/product_detail.html", {"product": product}) 

def update_product_view(request, shop_slug, slug):

	shop = get_object_or_404(Shop, slug=shop_slug)
	product_object = Product.objects.get(slug=slug, shop=shop)
	form = Product_Form(request.POST or None, instance=product_object)

	if request.method == "POST":

		if form.is_valid():

			form.save()

			return redirect(product_object)

	return render(request, "product/product_update.html", {"form": form})

def delete_product_view(request, shop_slug, slug):

	shop = get_object_or_404(Shop, slug=shop_slug)
	product_object = Product.objects.get(slug=slug, shop=shop)

	if request.method == "POST":

		product_object.delete()

		return redirect(reverse("shops:detail-shop", kwargs={"shop_slug": shop.slug}))

	return render(request, "product/product_delete.html", {"shop":shop, "product":product_object})

def shop_list_view(request):

	cart = Shopping_Cart(request)
	products = cart.create_products_list()
	customer = get_object_or_404(Profile, user=request.user)
	#total_prices = cart.get_total_price()

	if request.method == "POST":

		#panier = literal_eval(request.POST["panier"])
		print(request.POST)
		try:

			id = request.POST["Delete"]
			product = Product.objects.get(id=int(id))
			cart.remove_product(product, products)
			request.session.save()

		except KeyError as e:
			pass

		if request.POST["panier"] != "order":

			panier = cart.deserialize_json(request.POST["panier"])
			random_address = Address.objects.create(country="BE", city="some city", 
														street="a street", postal_code=1000)
			order = Order(paid=False, address=random_address, customer=customer, shoplist=panier)
			order.save()
			cart.clear_shopping(products)
			order_creation.send(sender=Order, user=customer, order=order)
		print(request.session["shopping_cart"])

	total_prices = cart.get_total_price()
		
	return render(request, "shops/shoplist.html", {"products": products, "total_cost": total_prices})

Shop_platform/shops/templates/shops/create_shop.html
<!DOCTYPE html>
<html>
<head>
<title></title>
<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>

</head>

{% block content %}
<body>
	<p> Hello {{request.user}}</p>

	{{request.session}}
	<form method="POST">
		{% csrf_token %}
	{% if products|length != 0 %}	
		<div value="{{products|length}}" id="products-length">
		{% for product in products %}

		<p id="name-{{forloop.counter0}}" value="{{product.name}} sold by {{product.seller}}">{{product.name}} - {{product.price}} - {{product.pk}}</p>
		
		
			{% comment %}
				<button class="close" aria-label="Close" value="{{product.pk}}" type="submit" id="{{product.pk}}" name="id" style="{text-align: center;}">Delete</button>
			{% endcomment %}

		<span>Quantity
			<span id="quantity-{{ forloop.counter0 }}" value="{{product.price}}"> {{product.quantity}} </span>
			<ion-icon id="up-{{ forloop.counter0 }}" name="caret-up-outline"></ion-icon>
			<ion-icon id="down-{{ forloop.counter0 }}" name="caret-down-outline"></ion-icon>
			<span id="price-{{ forloop.counter0 }}" >{{product.price}}</span>
		
		</span>
		<input type="hidden" value="test-{{forloop.counter0}}" name="{{product.name}}" >
		{% endfor %}

		<input type="hidden" value="order" name="panier" id="panier">
		<input type="submit" value="Create an Order" onclick="changeValue()">
		</form>
	{% else %}
		<p> votre panier est vide </p>

	{% endif %}

	</div>

	<p>Total: <span id="TotalCost">{{total_cost}}<span>euros </p>

<script>

	// take as argument an event 


	let productsLength = "{{products|length}}"
	productsLength = parseInt(productsLength);
	let finalBill = 0;

	function changeHtmlQuantity(id, content){

		document.getElementById("quantity-"+id).innerHTML = content.toString()
	};

	function changeHtmlPrice(id, content){

		document.getElementById("price-"+id).innerHTML = content.toString()
	};

	const productQuantity = {};

	for (let i = 0; i < productsLength; i++){
		let productName = document.getElementById("name-"+i).getAttribute("value");
		productQuantity[productName] = "1";

	};

	for (let i = 0; i < productsLength; i++){

		let btnUp = document.getElementById("up-"+i)
		let btnDown = document.getElementById("down-"+i)
		let quantity = document.getElementById("quantity-"+i).innerHTML;
		quantityHtml = quantity
		quantity = parseInt(quantity);
		let productName = document.getElementById("name-"+i).getAttribute("value");
		
		if (quantity >= 1){
					
					btnUp.addEventListener("click", function(){
						quantity++
						//debugger;
					changeHtmlQuantity(i, quantity)

					priceValue = document.getElementById("quantity-"+i).getAttribute("value")
					price = priceCalculation(priceValue, quantity)
					changeHtmlPrice(i, price)
					productQuantity[productName] = quantity.toString()
					});

					btnDown.addEventListener("click", function(){
						quantity--
						//debugger;
						changeHtmlQuantity(i, quantity)
						priceValue = document.getElementById("quantity-"+i).getAttribute("value")
						price = priceCalculation(priceValue, quantity)
						changeHtmlPrice(i, price)
						productQuantity[productName] = quantity.toString()
					});


			}

		function changeValue(){

		document.getElementById("panier").value = updateObject(productQuantity)
	}
	updateObject(productQuantity)

	};


	function totalCalculation(quantity, price){
		let totalBill = 0
		let bill = quantity * price 
		totalBill += bill;

		return totalBill

	};
	

	function priceCalculation(price, quantity){

		let priceUnique = parseFloat(price)
		let priceChanged = priceUnique * quantity
		
		priceChanged = priceChanged.toString()
		
		return priceChanged

	};

	function updateObject(obj){
		
		obj = JSON.stringify(obj)
		
		return obj
	};

	
</script>
</body>
{% endblock %}
</html>

Shop_platform/shops/templates/shops/detail_shop.html
<!DOCTYPE html>
<html>
<head>
<title></title>
</head>
{% block content %}
<body>
	<p> Hello {{request.user}}</p>

	{% if profile == shop.owner %}
		<p> Voici Votre Shop : {{shop.name}}</p>
	{% else %}
		Voici {{shop.name}}  cree par {{shop.owner}}
		
	{% endif %}

	{% for product in products %}

		<p><a href="{% url 'shops:detail-product' shop.slug product.slug %}">{{product.name}}</a> - {{product.price}} - {{product.description}}</p>
	{% endfor %}
	{% if profile == shop.owner %}
	<p><a href="{% url 'shops:create-product' %}">Create Product</a></p>

	{% endif %}
</body>
{% endblock %}
</html>

Shop_platform/shops/templates/shops/list_shop.html
<!DOCTYPE html>
<html>
<head>
<title></title>
</head>
{% block content %}
<body>
	
	{% for shop in shops %}

		<p><a href="{% url 'shops:detail-shop' shop.slug %}" >{{shop.name}}</a></p>

	{% endfor %}

</body>
{% endblock %}
</html>

Shop_platform/shops/templates/shops/shoplist.html
<!DOCTYPE html>
<html>
<head>
<title></title>
<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>

</head>

{% block content %}
<body>
	<p> Hello {{request.user}}</p>

	{{request.session}}
	<form method="POST">
		{% csrf_token %}
	{% if products|length != 0 %}	
		<div value="{{products|length}}" id="products-length">
		{% for product in products %}
		<form method="POST">
			{% csrf_token %}
		<p id="name-{{forloop.counter0}}" value="ID-{{product.pk}}">{{product.name}} - {{product.price}} - {{product.pk}}</p>
		
		
			
				<button class="close" aria-label="Close" value="{{product.pk}}" type="submit"  name="Delete" value="{{product.pk}}" style="{text-align: center;}">Delete</button>
			
		<form>
		<span>Quantity
			<span id="quantity-{{ forloop.counter0 }}" value="{{product.price}}"> {{product.quantity}} </span>
			<ion-icon id="up-{{ forloop.counter0 }}" name="caret-up-outline"></ion-icon>
			<ion-icon id="down-{{ forloop.counter0 }}" name="caret-down-outline"></ion-icon>
			<span id="price-{{ forloop.counter0 }}" >{{product.price}}</span>
		
		</span>
		{% endfor %}

		<input type="hidden" value="order" name="panier" id="panier">
		<input type="submit" value="Create an Order" onclick="changeValue()">
		</form>
	{% else %}
		<p> votre panier est vide </p>

	{% endif %}

	</div>

	<p>Total: <span id="TotalCost" value="{{total_cost}}">{{total_cost}}</span> euros </p>

<script>

	// take as argument an event 


	let productsLength = "{{products|length}}"
	productsLength = parseInt(productsLength);
	let totalBill = parseFloat(document.getElementById("TotalCost").getAttribute("value"))
	function changeHtmlQuantity(id, content){

		document.getElementById("quantity-"+id).innerHTML = content.toString()
	};

	function changeHtmlPrice(id, content){

		document.getElementById("price-"+id).innerHTML = content.toString()
	};

	const productQuantity = {};

	for (let i = 0; i < productsLength; i++){
		let productName = document.getElementById("name-"+i).getAttribute("value");
		productQuantity[productName] = "1";

	};

	for (let i = 0; i < productsLength; i++){

		let btnUp = document.getElementById("up-"+i)
		let btnDown = document.getElementById("down-"+i)
		let quantity = document.getElementById("quantity-"+i).innerHTML;
		quantityHtml = quantity
		quantity = parseInt(quantity);
		let productName = document.getElementById("name-"+i).getAttribute("value");
		
		if (quantity >= 1){
					
					btnUp.addEventListener("click", function(){
						quantity++
						//debugger;
					changeHtmlQuantity(i, quantity)

					priceValue = document.getElementById("quantity-"+i).getAttribute("value")
					price = priceCalculation(priceValue, quantity)
					changeHtmlPrice(i, price)
					productQuantity[productName] = quantity.toString()
					console.log(totalBill, "+", uniquePriceCalculation(i))
					totalBill += uniquePriceCalculation(i);
					console.log("egale = ", totalBill);
					changeTotalBillHtml(totalBill)

					});
					btnDown.addEventListener("click", function(){
						if (quantity > 1){
						quantity--
						//debugger;
						changeHtmlQuantity(i, quantity)
						priceValue = document.getElementById("quantity-"+i).getAttribute("value")
						price = priceCalculation(priceValue, quantity)
						changeHtmlPrice(i, price)
						productQuantity[productName] = quantity.toString()

					console.log(totalBill, "+", uniquePriceCalculation(i))
					totalBill -= uniquePriceCalculation(i);
					console.log('egale = ', totalBill);
					changeTotalBillHtml(totalBill);

					}
					});

			}

	function changeValue(){

		document.getElementById("panier").value = convertJSONObject(productQuantity)
	}
	convertJSONObject(productQuantity)

	};
	console.log("initial: ", totalBill, "euros")


	let totalCost = document.getElementById("TotalCost");

	function uniquePriceCalculation(id){

		let priceValue = parseFloat(document.getElementById("quantity-"+id).getAttribute("value"));

		return priceValue

	}

	function changeTotalBillHtml(total){

		document.getElementById("TotalCost").innerHTML = total;
	};


	function priceCalculation(price, quantity){

		let priceUnique = parseFloat(price)
		let priceChanged = priceUnique * quantity
		priceChanged.toFixed(2)
		priceChanged = priceChanged.toString()
		
		return priceChanged

	};

	function convertJSONObject(obj){
		
		obj = JSON.stringify(obj)
		
		return obj
	};


	
</script>
</body>
{% endblock %}
</html>