Shop_platform/Shop_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .settings import MEDIA_URL, MEDIA_ROOT 
from django.conf.urls.static import static
from shop_platform_app.views import home_view



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("home/", home_view, name="home_view"),
    path("api/", include("api.urls", namespace="shops-api")),
    path("shops/", include("shops.urls")),
    path("orders/", include("orders.urls")),
    path("notifications/", include("notifications.urls")),
	path("password_reset/", auth_views.PasswordResetView.as_view(), name="password-reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(MEDIA_URL, document_root=MEDIA_ROOT)

Shop_platform/api/urls.py
from rest_framework.routers import DefaultRouter 
from .views import ShopViewSet
from shops.models import Shop
from .serializers import ShopSerializer
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "api"

router = DefaultRouter()

router.register("Shops", ShopViewSet, basename="shop")
#router.register("products", ProductViewSet)

shop_list = ShopViewSet.as_view({"get":"list", "post":"create"})
shop_detail = ShopViewSet.as_view({"get":"retrieve"})

urlpatterns = [

    path("shops/", shop_list, name="shop-list"),
    path("shops/<slug:slug>/", shop_detail, name="shop-detail"),

]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=["json"])

Shop_platform/users/urls.py
from django.urls import path, include
from .views import home_view
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .views import User_Registration_View, profile_View, profile_other_user
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"

urlpatterns = [
	
	#path("", home_view, name="home"),
	path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
	path("registration/", User_Registration_View, name="registration"),
	path("logout/", auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
	path("accounts/profile/", profile_View, name="profile"),
	path("change-password/", auth_views.PasswordChangeView.as_view(success_url=reverse_lazy("users:password_change_done")), name="Change_password"),
	path("change-password/done", auth_views.PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
	path("accounts/<int:id>/", profile_other_user, name="Other_User_View"),
] 

Shop_platform/templates/password-reset/password_reset_complete.html
{% block content %}
  <p>
    Your password has been set. You may go ahead and <a href="{% url 'users:login' %}">sign in</a> now.
  </p>
{% endblock %}

Shop_platform/templates/password-reset/password_reset_confirm.html
{% block content %}
  {% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
{% endblock %}

Shop_platform/templates/password-reset/password_reset_done.html
{% block content %}
  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
{% endblock %}

Shop_platform/templates/password-reset/password_reset_form.html
{% block title %}Forgot Your Password?{% endblock %}

{% block content %}
  <h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
{% endblock %}