Shop_platform/Shop_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .settings import MEDIA_URL, MEDIA_ROOT 
from django.conf.urls.static import static
from shop_platform_app.views import home_view



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("home/", home_view, name="home_view"),
    path("api/", include("api.urls", namespace="shops-api")),
    path("shops/", include("shops.urls")),
    path("orders/", include("orders.urls")),
    path("notifications/", include("notifications.urls")),
	path("password_reset/", auth_views.PasswordResetView.as_view(), name="password-reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(MEDIA_URL, document_root=MEDIA_ROOT)

Shop_platform/api/urls.py
from rest_framework.routers import DefaultRouter 
from .views import ShopViewSet
from shops.models import Shop
from .serializers import ShopSerializer
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "api"

router = DefaultRouter()

router.register("Shops", ShopViewSet, basename="shop")
#router.register("products", ProductViewSet)

shop_list = ShopViewSet.as_view({"get":"list", "post":"create"})
shop_detail = ShopViewSet.as_view({"get":"retrieve"})

urlpatterns = [

    path("shops/", shop_list, name="shop-list"),
    path("shops/<slug:slug>/", shop_detail, name="shop-detail"),

]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=["json"])

Shop_platform/users/urls.py
from django.urls import path, include
from .views import home_view
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .views import User_Registration_View, profile_View, profile_other_user
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"

urlpatterns = [
	
	#path("", home_view, name="home"),
	path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
	path("registration/", User_Registration_View, name="registration"),
	path("logout/", auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
	path("accounts/profile/", profile_View, name="profile"),
	path("change-password/", auth_views.PasswordChangeView.as_view(success_url=reverse_lazy("users:password_change_done")), name="Change_password"),
	path("change-password/done", auth_views.PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
	path("accounts/<int:id>/", profile_other_user, name="Other_User_View"),
] 

Shop_platform/users/models.py
from django.db import models
from django.contrib.auth.models import User
import glob, os 
from PIL import Image

# Create your models here.

class Profile(models.Model):

	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default="nopicture.jpeg", upload_to="profilepicture")

	
	def __str__(self):

		return self.user.username

	def get_queryset(self):

		return self.user.objects.all() 

	def get_object(self):

		return self.user

	
	def save(self, **kwargs):

		super().save()

		size = 100, 100
		image = Image.open(self.image.path)
		image.thumbnail(size)
		image.save(self.image.path)

Shop_platform/users/forms.py
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import Profile

class User_Form(UserCreationForm):

	class Meta:

		model = User 
		fields = ["username", "password1", "password2", "email",
					"first_name", "last_name"]


class Profile_Form(ModelForm):


	class Meta:

		model = Profile
		exclude = ["user"]

Shop_platform/users/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import User_Form, Profile_Form
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.mail import send_mass_mail, send_mail
from Shop_platform.settings import EMAIL_HOST_USER
from .models import Profile
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from PIL import Image

def home_view(request):
	print(request)
	return render(request, "users/home.html", {})

def resize_image(self, picture):

		image = picture.resize((30, 30))

		return image 


def User_Registration_View(request):

	form = User_Form()

	if request.method == "POST":
		form = User_Form(request.POST)

		if form.is_valid():

			form.save()
			obj = get_object_or_404(User, username=request.POST["username"])
			Profile.objects.create(user=obj)

			user_mail = request.POST["email"]
			message = ("Hello there", "This is an automated message", EMAIL_HOST_USER, [user_mail])
			print("POST",EMAIL_HOST_USER, user_mail)
			send_mail("Hello there", "Hello, This is Your username: {} and your password {}".format(request.POST["username"], request.POST["password1"]), EMAIL_HOST_USER, ["karim.sadiki@gmail.com"])

			#return redirect("login")
			return HttpResponseRedirect("../login")
		
		return render(request, "users/signup.html", {"form":form})

	return render(request, "users/signup.html", {"form":form})
 
	
	#else:
	#	return render(request, "registration/signup.html", {"form":form})
		

def profile_View(request):

	form = Profile_Form()
	obj = get_object_or_404(Profile, user=request.user.id)
	if request.method == "POST":
		
		form = Profile_Form(request.POST, request.FILES, instance=obj)
		if form.is_valid():
			print(request.FILES)
			obj.image = request.FILES["image"]
			form.save()		

			

	return render(request, "users/profile.html", {"person":obj, "form":form})

@login_required(login_url="/login/")
def profile_logout_view(request):

	return render(request, "users/logout.html", {})

def profile_other_user(request, id):

	user = get_object_or_404(Profile, pk=id)
	return render(request, "users/profile_other_user.html", {"user":user})

Shop_platform/users/templates/users/home.html
<h1>Home Page</h1>

Shop_platform/users/templates/users/login.html
{% block content %}
<form method="POST" class="login_form">
	{% csrf_token %}
	<p>Login</p>
	{{form.as_p}}
		<input type="submit" name="Enter" class="le_btn">
						
		<small style="font-size:12px;"><a href="{% url 'password-reset' %}">Forgot your Password ?</a></small>
</form>

{% endblock %}

Shop_platform/users/templates/users/logout.html
{% extends "base.html"%}
{% block content %}
	<p> Vous etes deconnecte</p>

{% endblock %}

Shop_platform/users/templates/users/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}{% block main %}
<div  class="card">
<div  class="card-body">
<h4  class="card-title"> Change your password</h4><form  method="post">
{% csrf_token %}
{{ form|crispy }}<button  type="submit"  class="btn btn-success">Change password </button>
</form>
</div>
</div>
{% endblock %}

Shop_platform/users/templates/users/password_change_done.html
<p>Your password has been changed </p>

Shop_platform/users/templates/users/profile.html
{% block content%}
	
	<img src="{{person.image.url}}">
	<p>
		<label>Username:</label>

		{{person.user}}
	</p>
	<p>
		{{person.user.email}}
		{{person.image}}
	</p>
	<form method="POST" enctype="multipart/form-data">
	
		{% csrf_token %}
			{{form.as_p }}
			<input class="le_btn" value="Submit" type="submit">
	</form>
	<div class="div_contain">
		<a href="{% url 'users:Change_password' %} ">Change your password</a>

	</div>



{% endblock %}

Shop_platform/users/templates/users/profile_other_user.html
{% extends "registration/profile.html"%}

{% block content%}
	<img src="{{user.image.url}}">
	<p>{{user.user.first_name}} - {{user.user.last_name}}</p>
	<p> <label>Username:</label>{{user.user}}</p>
	<p>{{user.user.email}}</p>
	<p>{{user.auter_comment.post_set.all}}</p>
{% endblock %}

Shop_platform/users/templates/users/signup.html
{% block content %}
<form method="POST">
  	{% csrf_token %}
  	{% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
      
  <input type="submit" value="Sign in">
</form>

{% endblock %}